### PR TITLE
Remove dataset gateway

### PR DESCRIPTION
**Pull request by DrMattG**
I commented out the data_gateway if statement and that seems to work. I am not sure why that works or what the data_gateway was there for! Do you want to test this with some other data before we pull it in to the main? Also need to check what I have broken by fixing this....

### CODE REVIEW

**Comment by DrMattG** [comment]
I see now what the gateway was there for - we get an error the first time the data is loaded (as it is waiting for you to take an action). Once you click on any tab the data will appear

**Comment by DrMattG** [comment]
FFS! You can ignore this - I will leave it up until you have seen it though. I just reverted it back locally and the filter is working again.....

**Comment by DrMattG** [comment]
@nealhaddaway can you test something out for me. Start a new session - launch eviatlas and use the sample data. Then click on the map first so the points show and then on the map database. Does that allow you to filter? 

Then start another new session - launch again and select the sample data. Now this time go straight to the map database (do not pass go). Can you filter then?

**Comment by nealhaddaway** [comment]
No, the filter doesn't work unless the points are already plotted (your suggested click-through failed).

I also can't remove the filter - deleting the filter value and clicking filter aborts the session.

I had a really random error earlier where I filtered, then clicked through some other diagnostic plots, selected two fields to plot, then clicked filter and it repetitively cycled through on/off filtering without any intervention from me, essentially having a seizure until I aborted the session... Weird. This might need a substantial redesign to fix this shizzle...
________________________________

**Comment by DrMattG** [comment]
AAAAAAAARGH!!!! Back to the drawing board - agree we need a big redesign. I might cry first though

**Pull request closed without merging**
