### PR TITLE
Add loop for openstreetmap tiles

### PR DESCRIPTION
**Pull request by DrMattG**
Does this work? The problem is the OpenStreetMap tiles - no longer work with add_providerTiles and we need to switch to addTiles() if the user selects openstreetmap

### CODE REVIEW

**Comment by nealhaddaway** [comment]
No luck, I'm afraid. It's displaying in the app but not in the downloaded HTML... :(

**Comment by DrMattG** [comment]
Okay darn it! I’ll try again!

**Comment by DrMattG** [comment]
Weird - it works locally for me - not sure what I am doing wrong/right!
[eviAtlasMap2022-04-10.pdf](https://github.com/ESHackathon/eviatlas/files/8458563/eviAtlasMap2022-04-10.pdf)
eviAtlasMap2022-04-10
image

**Comment by nealhaddaway** [comment]
That is weird! Do you want to try pushing it to shiny apps? Maybe it’s something wrong with my package libraries? I’ve updated everything but maybe it didn’t work…

Sent from my iPhone

On 10 Apr 2022, at 09:20, Matthew Grainger ***@***.***> wrote:

﻿

Weird - it works locally for me - not sure what I am doing wrong/right!
eviAtlasMap2022-04-10.pdf<https://github.com/ESHackathon/eviatlas/files/8458563/eviAtlasMap2022-04-10.pdf>
[eviAtlasMap2022-04-10]<https://user-images.githubusercontent.com/11541781/162609402-5c8bbafa-a2a5-43c9-985b-ff42950ab3ab.png>
[image]<https://user-images.githubusercontent.com/11541781/162609427-ade8f0a5-b1d4-4cb8-b508-ec99398e29e0.png>

**Comment by DrMattG** [comment]
I deployed it via my own account and it seems to work - https://drmatt.shinyapps.io/eviatlas/ 

I will delete it later on

**Comment by nealhaddaway** [comment]
Ooooh amazing thanks! Damn it.. how has this been all my fault 😂
Shall we chat on Twitter so you have rights to deploy to Shiny?

Sent from my iPhone

On 10 Apr 2022, at 09:53, Matthew Grainger ***@***.***> wrote:

﻿

I deployed it via my own account and it seems to work - https://drmatt.shinyapps.io/eviatlas/

I will delete it later on

**Pull request merged**
